#!/usr/bin/env python3

from curses import wrapper, panel
import curses

curses.initscr()
pad1 = curses.newwin(40, 40) #creating a window that is 40x40

gamemap = '''.........................
............................
............................
...........................
..............................
.............................
............................
...............................
...........................
............................
...........................
............................
.............................
................................
..............................
..........................
..........................
............................
..............................
...............................
................................
.............................'''


def main(stdscr):
    curses.initscr()
    pad1.addstr(0, 0, gamemap)
    curses.init_pair(1, curses.COLOR_RED, curses.COLOR_BLACK)
    pad1.addch(5, 5, 'D', curses.A_REVERSE)
    pad1.addstr(7, 7, 'DDDDDDDDD', curses.color_pair(1))
    pad1.refresh()
    while True:
        answer = stdscr.getkey()
        if answer == '':
            pad1.addstr(3, 3, 'space')
        elif answer == ' ':
            pad1.addstr(3, 3, 'spaace')
        elif answer == '''
''':
            pad1.addstr(3, 3, '/n')
        else:
            pad1.addstr(3, 3, answer)
        pad1.refresh()

wrapper(main)



